namespace NSGE.Infrastructure.SQLBuilder.Operacional
{
    public class OrdemServicoSQLContainer
    {
        public string GetOrdemServico()
        {
            return @"SELECT O.Id, O.NumeroDaOS, O.Nome, P.Nome as NomeCliente, O.InicioDoEvento
                      FROM OrdemServico O LEFT JOIN pessoa P on P.Id = O.IdDoCliente order by InicioDoEvento DESC Limit 200";
        }

        public string GetAllOrdemServicoEntrada()
        {
            return @"select * from view_entradaitens group by IdTransacao order by Data desc limit 0, 200";
        }

        public string GetHistoricoEstoque()
        {
            return @"SELECT p.Nome as ProdutoNome, e.CodigoInterno , os.NumeroDaOs as NumeroDaOs, os.Nome as EventoNome, pe.Nome as ClienteNome, s.Descricao as StatusDescricao, 
                            os.DataDeAlteracao FROM HistoricoEstoque he
                            inner join estoque e on e.Id = he.IdEstoque
                            inner join ordemservico os on os.Id = he.IdOrdemServico
                            inner join status s on s.Id = he.IdStatus
                            inner join produto p on p.Id = e.IdProduto
                            inner join pessoa pe on pe.Id = os.IdDoCliente
                            order by DataDeAlteracao DESC
                            limit 0, 2000";
        }

        public string GetTransationById()
        {
            return @"SELECT
                        VE.Id, 
                        VE.IdTransacao, 
                        VE.NumeroDaOS, 
                        VE.Evento, 
                        VE.Cliente, 
                        VE.Usuario, 
                        VE.Data, 
                        VE.Produto, 
                        VE.CodigoInterno, 
                        VE.Quantidade, 
                        VE.Status, 
                        VE.TipoEntrada, 
                        VE.Tabela
                            FROM View_EntradaItens VE
                                WHERE (VE.IdTransacao = @Id) OR ((VE.IdTransacao IS  NULL) AND (@Id IS  NULL))
                                    ORDER BY 
                                        VE.NumeroDaOS ASC";
        }

        public string Load()
        {
            return @"SELECT
                        `Project2`.`C1`, 
                        `Project2`.`Id`, 
                        `Project2`.`NumeroDaOS`, 
                        `Project2`.`Nome`, 
                        `Project2`.`IdDoRepresentanteComercial`, 
                        `Project2`.`IdDoCliente`, 
                        `Project2`.`IdDoAlmoxarife`, 
                        `Project2`.`InicioDoEvento`, 
                        `Project2`.`FimDoEvento`, 
                        `Project2`.`DataDaMontagem`, 
                        `Project2`.`HoraDaMontagem`, 
                        `Project2`.`DataDeSaida`, 
                        `Project2`.`DataDeRetorno`, 
                        `Project2`.`LocalId`, 
                        `Project2`.`EnderecoId`, 
                        `Project2`.`IdDoEvento`, 
                        `Project2`.`DataDeCadastro`, 
                        `Project2`.`DataDeAlteracao`, 
                        `Project2`.`UsuarioCadastroId`, 
                        `Project2`.`UsuarioAlteracaoId`, 
                        `Project2`.`Discriminator`, 
                        `Project2`.`Id1`, 
                        `Project2`.`Nome1`, 
                        `Project2`.`Documento`, 
                        `Project2`.`DataNascimento`, 
                        `Project2`.`NomeFantasia`, 
                        `Project2`.`TipoPessoa`, 
                        `Project2`.`Cliente` as Cliente1, 
                        `Project2`.`Fornecedor` as Fornecedor1, 
                        `Project2`.`Funcionario` as Funcionario1, 
                        `Project2`.`Sublocacao` as Sublocacao1,  
                        `Project2`.`Freelancer` as Freelancer1, 
                        `Project2`.`Transportadora` as Transportadora, 
                        `Project2`.`Motorista` as Motorista1, 
                        `Project2`.`Tecnico` as Tecnico1, 
                        `Project2`.`RepresentanteComercial` as RepresentanteComercial1, 
                        `Project2`.`Produtor` as Produtor1, 
                        `Project2`.`Almoxarife` as Almoxarife1, 
                        `Project2`.`ReferenciaBancaria`, 
                        `Project2`.`Email`, 
                        `Project2`.`PaginaWeb`, 
                        `Project2`.`Observacao`, 
                        `Project2`.`UsuarioCadastroId1`, 
                        `Project2`.`UsuarioAlteracaoId1`, 
                        `Project2`.`DataDeCadastro1`, 
                        `Project2`.`DataDeAlteracao1`, 
                        `Project2`.`AlimentacaoRJ`, 
                        `Project2`.`AlimentacaoForaRJ`, 
                        `Project2`.`DiariaTecnica`, 
                        `Project2`.`DiariaCoordenador`, 
                        `Project2`.`Imagem`, 
                        `Project2`.`IdStatus`, 
                        `Project2`.`IsEstrangeiro`, 
                        `Project2`.`NomePai`, 
                        `Project2`.`NomeMae`, 
                        `Project2`.`Identidade`, 
                        `Project2`.`Orgao`, 
                        `Project2`.`DataDeEmissao`, 
                        `Project2`.`Sexo`, 
                        `Project2`.`EstadoCivil`, 
                        `Project2`.`Profissao`, 
                        `Project2`.`Naturalidade`, 
                        `Project2`.`InscricaoEstadual`, 
                        `Project2`.`InscricaoMunicipal`, 
                        `Project2`.`Discriminator1`, 
                        `Project2`.`Id2`, 
                        `Project2`.`Nome2`, 
                        `Project2`.`Documento1`, 
                        `Project2`.`DataNascimento1`, 
                        `Project2`.`NomeFantasia1`, 
                        `Project2`.`TipoPessoa1`, 
                        `Project2`.`Cliente1`, 
                        `Project2`.`Fornecedor1`, 
                        `Project2`.`Funcionario1`, 
                        `Project2`.`Sublocacao1`, 
                        `Project2`.`Freelancer1`, 
                        `Project2`.`Transportadora1`, 
                        `Project2`.`Motorista1`, 
                        `Project2`.`Tecnico1`, 
                        `Project2`.`RepresentanteComercial1`, 
                        `Project2`.`Produtor1`, 
                        `Project2`.`Almoxarife1`, 
                        `Project2`.`ReferenciaBancaria1`, 
                        `Project2`.`Email1`, 
                        `Project2`.`PaginaWeb1`, 
                        `Project2`.`Observacao1`, 
                        `Project2`.`UsuarioCadastroId2`, 
                        `Project2`.`UsuarioAlteracaoId2`, 
                        `Project2`.`DataDeCadastro2`, 
                        `Project2`.`DataDeAlteracao2`, 
                        `Project2`.`AlimentacaoRJ1`, 
                        `Project2`.`AlimentacaoForaRJ1`, 
                        `Project2`.`DiariaTecnica1`, 
                        `Project2`.`DiariaCoordenador1`, 
                        `Project2`.`Imagem1`, 
                        `Project2`.`IdStatus1`, 
                        `Project2`.`IsEstrangeiro1`, 
                        `Project2`.`NomePai1`, 
                        `Project2`.`NomeMae1`, 
                        `Project2`.`Identidade1`, 
                        `Project2`.`Orgao1`, 
                        `Project2`.`DataDeEmissao1`, 
                        `Project2`.`Sexo1`, 
                        `Project2`.`EstadoCivil1`, 
                        `Project2`.`Profissao1`, 
                        `Project2`.`Naturalidade1`, 
                        `Project2`.`InscricaoEstadual1`, 
                        `Project2`.`InscricaoMunicipal1`, 
                        `Project2`.`C2`, 
                        `Project2`.`Id3`, 
                        `Project2`.`ContatoId`, 
                        `Project2`.`OrdemServicoId`
                        FROM (SELECT
                        `Limit1`.`Id`, 
                        `Limit1`.`NumeroDaOS`, 
                        `Limit1`.`Nome`, 
                        `Limit1`.`IdDoRepresentanteComercial`, 
                        `Limit1`.`IdDoCliente`, 
                        `Limit1`.`IdDoAlmoxarife`, 
                        `Limit1`.`InicioDoEvento`, 
                        `Limit1`.`FimDoEvento`, 
                        `Limit1`.`DataDaMontagem`, 
                        `Limit1`.`HoraDaMontagem`, 
                        `Limit1`.`DataDeSaida`, 
                        `Limit1`.`DataDeRetorno`, 
                        `Limit1`.`LocalId`, 
                        `Limit1`.`EnderecoId`, 
                        `Limit1`.`IdDoEvento`, 
                        `Limit1`.`DataDeCadastro`, 
                        `Limit1`.`DataDeAlteracao`, 
                        `Limit1`.`UsuarioCadastroId`, 
                        `Limit1`.`UsuarioAlteracaoId`, 
                        `Limit1`.`Id1`, 
                        `Limit1`.`Nome1`, 
                        `Limit1`.`Documento`, 
                        `Limit1`.`DataNascimento`, 
                        `Limit1`.`NomeFantasia`, 
                        `Limit1`.`TipoPessoa`, 
                        `Limit1`.`Cliente`, 
                        `Limit1`.`Fornecedor`, 
                        `Limit1`.`Funcionario`, 
                        `Limit1`.`Sublocacao`, 
                        `Limit1`.`Freelancer`, 
                        `Limit1`.`Transportadora`, 
                        `Limit1`.`Motorista`, 
                        `Limit1`.`Tecnico`, 
                        `Limit1`.`RepresentanteComercial`, 
                        `Limit1`.`Produtor`, 
                        `Limit1`.`Almoxarife`, 
                        `Limit1`.`ReferenciaBancaria`, 
                        `Limit1`.`Email`, 
                        `Limit1`.`PaginaWeb`, 
                        `Limit1`.`Observacao`, 
                        `Limit1`.`UsuarioCadastroId1`, 
                        `Limit1`.`UsuarioAlteracaoId1`, 
                        `Limit1`.`DataDeCadastro1`, 
                        `Limit1`.`DataDeAlteracao1`, 
                        `Limit1`.`AlimentacaoRJ`, 
                        `Limit1`.`AlimentacaoForaRJ`, 
                        `Limit1`.`DiariaTecnica`, 
                        `Limit1`.`DiariaCoordenador`, 
                        `Limit1`.`Imagem`, 
                        `Limit1`.`IdStatus`, 
                        `Limit1`.`IsEstrangeiro`, 
                        `Limit1`.`NomePai`, 
                        `Limit1`.`NomeMae`, 
                        `Limit1`.`Identidade`, 
                        `Limit1`.`Orgao`, 
                        `Limit1`.`DataDeEmissao`, 
                        `Limit1`.`Sexo`, 
                        `Limit1`.`EstadoCivil`, 
                        `Limit1`.`Profissao`, 
                        `Limit1`.`Naturalidade`, 
                        `Limit1`.`InscricaoEstadual`, 
                        `Limit1`.`InscricaoMunicipal`, 
                        `Limit1`.`Discriminator`, 
                        `Limit1`.`Id2`, 
                        `Limit1`.`Nome2`, 
                        `Limit1`.`Documento1`, 
                        `Limit1`.`DataNascimento1`, 
                        `Limit1`.`NomeFantasia1`, 
                        `Limit1`.`TipoPessoa1`, 
                        `Limit1`.`Cliente1`, 
                        `Limit1`.`Fornecedor1`, 
                        `Limit1`.`Funcionario1`, 
                        `Limit1`.`Sublocacao1`, 
                        `Limit1`.`Freelancer1`, 
                        `Limit1`.`Transportadora1`, 
                        `Limit1`.`Motorista1`, 
                        `Limit1`.`Tecnico1`, 
                        `Limit1`.`RepresentanteComercial1`, 
                        `Limit1`.`Produtor1`, 
                        `Limit1`.`Almoxarife1`, 
                        `Limit1`.`ReferenciaBancaria1`, 
                        `Limit1`.`Email1`, 
                        `Limit1`.`PaginaWeb1`, 
                        `Limit1`.`Observacao1`, 
                        `Limit1`.`UsuarioCadastroId2`, 
                        `Limit1`.`UsuarioAlteracaoId2`, 
                        `Limit1`.`DataDeCadastro2`, 
                        `Limit1`.`DataDeAlteracao2`, 
                        `Limit1`.`AlimentacaoRJ1`, 
                        `Limit1`.`AlimentacaoForaRJ1`, 
                        `Limit1`.`DiariaTecnica1`, 
                        `Limit1`.`DiariaCoordenador1`, 
                        `Limit1`.`Imagem1`, 
                        `Limit1`.`IdStatus1`, 
                        `Limit1`.`IsEstrangeiro1`, 
                        `Limit1`.`NomePai1`, 
                        `Limit1`.`NomeMae1`, 
                        `Limit1`.`Identidade1`, 
                        `Limit1`.`Orgao1`, 
                        `Limit1`.`DataDeEmissao1`, 
                        `Limit1`.`Sexo1`, 
                        `Limit1`.`EstadoCivil1`, 
                        `Limit1`.`Profissao1`, 
                        `Limit1`.`Naturalidade1`, 
                        `Limit1`.`InscricaoEstadual1`, 
                        `Limit1`.`InscricaoMunicipal1`, 
                        `Limit1`.`Discriminator1`, 
                        `Limit1`.`C1`, 
                        `Extent4`.`Id` AS `Id3`, 
                        `Extent4`.`ContatoId`, 
                        `Extent4`.`OrdemServicoId`, 
                        CASE WHEN (`Extent4`.`Id` IS  NULL) THEN (NULL)  ELSE (1) END AS `C2`
                        FROM (SELECT
                        `Extent1`.`Id`, 
                        `Extent1`.`NumeroDaOS`, 
                        `Extent1`.`Nome`, 
                        `Extent1`.`IdDoRepresentanteComercial`, 
                        `Extent1`.`IdDoCliente`, 
                        `Extent1`.`IdDoAlmoxarife`, 
                        `Extent1`.`InicioDoEvento`, 
                        `Extent1`.`FimDoEvento`, 
                        `Extent1`.`DataDaMontagem`, 
                        `Extent1`.`HoraDaMontagem`, 
                        `Extent1`.`DataDeSaida`, 
                        `Extent1`.`DataDeRetorno`, 
                        `Extent1`.`LocalId`, 
                        `Extent1`.`EnderecoId`, 
                        `Extent1`.`IdDoEvento`, 
                        `Extent1`.`DataDeCadastro`, 
                        `Extent1`.`DataDeAlteracao`, 
                        `Extent1`.`UsuarioCadastroId`, 
                        `Extent1`.`UsuarioAlteracaoId`, 
                        `Extent2`.`Id` AS `Id1`, 
                        `Extent2`.`Nome` AS `Nome1`, 
                        `Extent2`.`Documento`, 
                        `Extent2`.`DataNascimento`, 
                        `Extent2`.`NomeFantasia`, 
                        `Extent2`.`TipoPessoa`, 
                        `Extent2`.`Cliente`, 
                        `Extent2`.`Fornecedor`, 
                        `Extent2`.`Funcionario`, 
                        `Extent2`.`Sublocacao`, 
                        `Extent2`.`Freelancer`, 
                        `Extent2`.`Transportadora`, 
                        `Extent2`.`Motorista`, 
                        `Extent2`.`Tecnico`, 
                        `Extent2`.`RepresentanteComercial`, 
                        `Extent2`.`Produtor`, 
                        `Extent2`.`Almoxarife`, 
                        `Extent2`.`ReferenciaBancaria`, 
                        `Extent2`.`Email`, 
                        `Extent2`.`PaginaWeb`, 
                        `Extent2`.`Observacao`, 
                        `Extent2`.`UsuarioCadastroId` AS `UsuarioCadastroId1`, 
                        `Extent2`.`UsuarioAlteracaoId` AS `UsuarioAlteracaoId1`, 
                        `Extent2`.`DataDeCadastro` AS `DataDeCadastro1`, 
                        `Extent2`.`DataDeAlteracao` AS `DataDeAlteracao1`, 
                        `Extent2`.`AlimentacaoRJ`, 
                        `Extent2`.`AlimentacaoForaRJ`, 
                        `Extent2`.`DiariaTecnica`, 
                        `Extent2`.`DiariaCoordenador`, 
                        `Extent2`.`Imagem`, 
                        `Extent2`.`IdStatus`, 
                        `Extent2`.`IsEstrangeiro`, 
                        `Extent2`.`NomePai`, 
                        `Extent2`.`NomeMae`, 
                        `Extent2`.`Identidade`, 
                        `Extent2`.`Orgao`, 
                        `Extent2`.`DataDeEmissao`, 
                        `Extent2`.`Sexo`, 
                        `Extent2`.`EstadoCivil`, 
                        `Extent2`.`Profissao`, 
                        `Extent2`.`Naturalidade`, 
                        `Extent2`.`InscricaoEstadual`, 
                        `Extent2`.`InscricaoMunicipal`, 
                        `Extent2`.`Discriminator`, 
                        `Extent3`.`Id` AS `Id2`, 
                        `Extent3`.`Nome` AS `Nome2`, 
                        `Extent3`.`Documento` AS `Documento1`, 
                        `Extent3`.`DataNascimento` AS `DataNascimento1`, 
                        `Extent3`.`NomeFantasia` AS `NomeFantasia1`, 
                        `Extent3`.`TipoPessoa` AS `TipoPessoa1`, 
                        `Extent3`.`Cliente` AS `Cliente1`, 
                        `Extent3`.`Fornecedor` AS `Fornecedor1`, 
                        `Extent3`.`Funcionario` AS `Funcionario1`, 
                        `Extent3`.`Sublocacao` AS `Sublocacao1`, 
                        `Extent3`.`Freelancer` AS `Freelancer1`, 
                        `Extent3`.`Transportadora` AS `Transportadora1`, 
                        `Extent3`.`Motorista` AS `Motorista1`, 
                        `Extent3`.`Tecnico` AS `Tecnico1`, 
                        `Extent3`.`RepresentanteComercial` AS `RepresentanteComercial1`, 
                        `Extent3`.`Produtor` AS `Produtor1`, 
                        `Extent3`.`Almoxarife` AS `Almoxarife1`, 
                        `Extent3`.`ReferenciaBancaria` AS `ReferenciaBancaria1`, 
                        `Extent3`.`Email` AS `Email1`, 
                        `Extent3`.`PaginaWeb` AS `PaginaWeb1`, 
                        `Extent3`.`Observacao` AS `Observacao1`, 
                        `Extent3`.`UsuarioCadastroId` AS `UsuarioCadastroId2`, 
                        `Extent3`.`UsuarioAlteracaoId` AS `UsuarioAlteracaoId2`, 
                        `Extent3`.`DataDeCadastro` AS `DataDeCadastro2`, 
                        `Extent3`.`DataDeAlteracao` AS `DataDeAlteracao2`, 
                        `Extent3`.`AlimentacaoRJ` AS `AlimentacaoRJ1`, 
                        `Extent3`.`AlimentacaoForaRJ` AS `AlimentacaoForaRJ1`, 
                        `Extent3`.`DiariaTecnica` AS `DiariaTecnica1`, 
                        `Extent3`.`DiariaCoordenador` AS `DiariaCoordenador1`, 
                        `Extent3`.`Imagem` AS `Imagem1`, 
                        `Extent3`.`IdStatus` AS `IdStatus1`, 
                        `Extent3`.`IsEstrangeiro` AS `IsEstrangeiro1`, 
                        `Extent3`.`NomePai` AS `NomePai1`, 
                        `Extent3`.`NomeMae` AS `NomeMae1`, 
                        `Extent3`.`Identidade` AS `Identidade1`, 
                        `Extent3`.`Orgao` AS `Orgao1`, 
                        `Extent3`.`DataDeEmissao` AS `DataDeEmissao1`, 
                        `Extent3`.`Sexo` AS `Sexo1`, 
                        `Extent3`.`EstadoCivil` AS `EstadoCivil1`, 
                        `Extent3`.`Profissao` AS `Profissao1`, 
                        `Extent3`.`Naturalidade` AS `Naturalidade1`, 
                        `Extent3`.`InscricaoEstadual` AS `InscricaoEstadual1`, 
                        `Extent3`.`InscricaoMunicipal` AS `InscricaoMunicipal1`, 
                        `Extent3`.`Discriminator` AS `Discriminator1`, 
                        1 AS `C1`
                        FROM `OrdemServico` AS `Extent1` 
                        LEFT OUTER JOIN `Pessoa` AS `Extent2` ON ((`Extent2`.`Discriminator` = 'PessoaFisica') OR (`Extent2`.`Discriminator` = 'PessoaJuridica')) AND (`Extent1`.`IdDoCliente` = `Extent2`.`Id`) 
                        LEFT OUTER JOIN `Pessoa` AS `Extent3` ON ((`Extent3`.`Discriminator` = 'PessoaFisica') OR (`Extent3`.`Discriminator` = 'PessoaJuridica')) AND (`Extent1`.`IdDoRepresentanteComercial` = `Extent3`.`Id`)
                         WHERE `Extent1`.`Id` = @Id LIMIT 1) AS `Limit1` 
                        LEFT OUTER JOIN `ContatoOrdemServico` AS `Extent4` ON `Limit1`.`Id` = `Extent4`.`OrdemServicoId`) AS `Project2`
                         ORDER BY 
                        `Project2`.`Id` ASC, 
                        `Project2`.`Id1` ASC, 
                        `Project2`.`Id2` ASC, 
                        `Project2`.`C2` ASC
";
        }

        public string Filtrar()
        {
            return @"SELECT
                        Id, 
                        IdOrdemServico, 
                        IdUsuario, 
                        TextoNovo, 
                        Data
                            FROM ObservacaoOrdemServico
                                WHERE (IdOrdemServico = @Id) OR ((IdOrdemServico IS  NULL) AND (@Id IS  NULL)) LIMIT 1";
        }
    }
}